alter table public.expense_payers drop constraint expense_payers_amount_check;
alter table public.expense_payers add constraint expense_payers_amount_check check (amount > 0 and amount <= 9007199254740991);
alter table public.expenses drop constraint expenses_amount_valid;
alter table public.expenses add constraint expenses_amount_valid check (amount > 0 and amount <= 9007199254740991);
create or replace function private.validate_expense_input(target_event_id uuid, target_concept text, target_category text, target_amount bigint, target_payer_ids uuid[], target_payer_amounts bigint[], target_participant_ids uuid[], allow_historical boolean default false, historical_payer_ids uuid[] default '{}'::uuid[], historical_participant_ids uuid[] default '{}'::uuid[]) returns void language plpgsql security definer set search_path='' as $$ begin
 if target_concept<>btrim(target_concept) or char_length(target_concept) not between 1 and 100 or target_concept~'[[:cntrl:]]' then raise exception 'Invalid expense concept.' using errcode='22023'; end if;
 if target_category not in ('food','drink','alcohol','cannabis','other') or target_amount<=0 or target_amount>9007199254740991 then raise exception 'Invalid expense input.' using errcode='22023'; end if;
 if coalesce(array_length(target_payer_ids,1),0)=0 or array_length(target_payer_ids,1)<>array_length(target_payer_amounts,1) or (select count(*) from unnest(target_payer_ids) x)<>(select count(distinct x) from unnest(target_payer_ids) x) or (select coalesce(sum(x),0) from unnest(target_payer_amounts) x)<>target_amount or exists(select 1 from unnest(target_payer_amounts) x where x<=0 or x>9007199254740991) then raise exception 'Payer amounts must exactly equal the expense amount.' using errcode='22023'; end if;
 if coalesce(array_length(target_participant_ids,1),0)=0 or (select count(*) from unnest(target_participant_ids)x)<>(select count(distinct x) from unnest(target_participant_ids)x) then raise exception 'At least one unique consumer is required.' using errcode='22023'; end if;
 if exists(select 1 from unnest(target_payer_ids) x left join public.participants p on p.id=x and p.event_id=target_event_id where p.id is null or (not p.active and (not allow_historical or not x=any(historical_payer_ids)))) then raise exception 'Payers must be active event participants.' using errcode='22023'; end if;
 if exists(select 1 from unnest(target_participant_ids) x left join public.participants p on p.id=x and p.event_id=target_event_id where p.id is null or (not p.active and (not allow_historical or not x=any(historical_participant_ids)))) then raise exception 'Consumers must be active event participants.' using errcode='22023'; end if;
end $$;
